---
title: "Assignment 4"
subtitle: "DSE 511"
date: "Assigned 2022-11-17 --- Due 2022-12-5 11:59pm"
output: 
    - pdf_document
urlcolor: blue
linkcolor: blue
---

## Instructions

**READ THE INSTRUCTIONS CAREFULLY**

Prepare your answers in a presentable document (Word, LaTeX, pdf generated from markdown, ...). When you are completed, submit your final document on Canvas. Please also submit a separate plain text file (no markup) with easily copy/paste-able code.

For coding problems, you are not allowed to use R or Python. You should only need the tools discussed in class, e.g. `sed`, `grep`, `cat`, ...

Suggestion: test your scripts! Write your own test cases.

Reminder that you ***may not*** copy code from each other. Doing so will be considered academic dishonesty; please refer to the syllabus.

## Problems

1. (10%) You are in a slack group and observe a conversation between two software engineers. The first says "Looks like there's a bug in compute_client_metadata()". The second responds "s/compute/update/". Briefly explain what the second engineer meant by their strange response.

2. (10%) Go to your terminal and start an interactive program, like `nano`, `R`, or `Python`. Press `ctrl`+`z`. Explain what just happened and what command to enter to restore your program.

3. (10%) Someone gives you access to their server, and says that your home directory is in an unusual place. In the opening email, they say it is at `/users/${YOUR_LAST_NAME}/${YOUR_FIRST_NAME}/`. Where is **your** home directory on this server?

4. (10%) Suppose you are given a file `email_or_name.txt` that contains either a valid email address or a person's legal name, one per line. Write a shell script that tells you how many email addresses are in the file. (Hint: what character does a valid email address have that no legal name should?).

5. (10%) Write a shell script that lists the 3 largest files in the current working directory (non-recursive). The sizes should be in a human-readable format, and the files should be listed from largest to smallest. (Hint: `man du`).

6. (10%) Write a shell script that loops over a file named `urls.txt` that contains a list of potential URL's, one per line, and prints "EXISTS: ${URL}" if the url exists, and otherwise prints nothing. (Hint: use `wget --method=HEAD`)

7. (20%) Write a shell script that will create 100 files. Each file will contain the integer number of that file starting at 0, then 1, all the way to 99. The name of each file should be `file${NUMBER}.txt`, where the number in the file name (but not the file itself) contains a leading 0 if the number is less than 10. 

8. (20%) Write a shell script that will loop over files that are named as in problem 4 above (assume that only they are in your current working directory), and bulk rename them to contain two additional leading zeros. You may assume that each file is named `file${NUMBER}.txt`.
